customhost = "employee.c9tlv938h2zq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "kongbangyong-employee"
customregion = "us-east-1"
